<property>
<name>fs.s3a.impl</name>
   <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
</property>
<property>
   <name>fs.s3a.access.key</name>
   <value>YOUR_ACCESS_KEY</value>
</property>
<property>
   <name>fs.s3a.secret.key</name>
   <value>YOUR_SECRET_KEY</value>
</property>
